### ISSUE TITLE
questions about the .ply file

### ISSUE THREAD

**Issue by MachineGUN001** [HaotianZhangAI4Science/SurfGen#10]
hi, Haotian,

Thank you so much for being so productive and efficient in researching these moleclues generation methods. The previous discussion asked about Resgen's method, and the results from it looks like the generated molecules are not very fit for pocket adaptation. And Surfgen seems to address this problem better by generating surfaces. I think your idea is very promising.

I tried to run generate surface and found quite a lot of problems, I checked the code and the generation of ply file mainly relies on pymesh2, I used pymesh before and found that from_mesh() is missing. But pymesh2 doesn't seem to support windows OS.

my OS system is windows10, could you provide some suggestions how can I generate the .ply file under windows10.

many many thanks,

best,
Sh-Y

**Comment by HaotianZhangAI4Science** [comment]
Dear Sh-Y,

Thank you for your kind words! I agree that the compatibility issue with pymesh2, being limited to Python 2.X on Linux, poses a significant challenge. To address this, we're considering two potential solutions: developing an online website or updating pymesh2 for Python 3.X compatibility.

In the coming months, we plan to launch an online platform for generating .ply files, which should offer a more accessible solution. Meanwhile, if you have any files you need processed beforehand, please don't hesitate to email them to me, and I'll be happy to assist.

Warm regards,

Odin

**Comment by MachineGUN001** [comment]
@HaotianZhangAI4Science thanks for your helps so much.
I send email to you. 

Best,
Sh-Y
